### ISSUE TITLE
Router onUpdate called twice

### ISSUE THREAD

**Issue by codingdash** [reactjs/react-router#3643]
**Issue -** When we trigger any route change event, the ``onUpdate`` method getting invoked twice.

Sample code structure-

```
const appHistory = useRouterHistory(createHashHistory)({ queryKey: false });
var counter = 0;
ReactDOM.render(
    <Router history={appHistory} onUpdate={() => {
        //this will get invoked twice
        console.log("Router got updated and counter is " + counter);
    }}>
        ...
    </Router>,
    appDOM
);
```
When I was going through the flow, in ``createTransitionManager.js`` I had seen one comment in ``listen``  method-

```
    // TODO: Only use a single history listener. Otherwise we'll
    // end up with multiple concurrent calls to match.
```

Does it relate to the same issue? Had anyone experienced this issue?

**Comment by timdorr** [comment]
Establish your appHistory object as a singleton module, like we do with the provided histories. How are you triggering your route changes, via Links or push on the history instance?

**Comment by taion** [comment]
This is probably because you're using a `<a href="#foo">` instead of a `<Link>`. Use `<Link>` instead.

**Comment by codingdash** [comment]
Hi @taion @timdorr , Thanks for the inputs.

I was using ``<Link>`` component only. But the issue was the ``to`` param. Earlier I was using it like ``to="bingo"``(which was being converted to ``localhost/#bingo``), after changing it to ``to="/bingo"``(which is being converted to ``localhost/#/bingo``) the issue was resolved. The two call to ``onUpdate`` was expected here because it was causing redirect.

Thanks again 😃

**Comment by rolaru** [comment]
@taion @timdorr, I used <Link> the way @codingdash mentioned and still have trouble with onUpdate being called twice.

**Comment by MaxiSantos** [comment]
I'm still having this issue and I'm using Link component. I'm using react-router 3.0.5.
I ended up using something like this:

`
<Router onUpdate={() => {
        if (this.state.location.action == "PUSH") {
           this.fireTracking()}
        }
} history={ hashHistory }>
`
I noticed the action is different the two times the onUpdate is being called: PUSH and then POP.

**Comment by MaxiSantos** [comment]
I'm still having this issue and I'm using Link component. I'm using react-router 3.0.5.
I ended up using something like this:
`
<Router onUpdate={
        function(){
          if (this.state && this.state.location.action == "PUSH") {
            fireTracking();
          }
        }
      } history={ hashHistory }>
`

I noticed the action is different the two times the onUpdate is being called: PUSH and then POP.
